### ISSUE TITLE
New Comments?

### ISSUE THREAD

**Issue by DeysonOrtiz** [ravinderk/WP-Realtime-Notify#1]
Hello and good day.

Will there be a way to notify users of new comments?  Similar to social sites where we can see when a new comment is added or posted.

Thank you and have a lovely day :)

**Comment by ravinderk** [comment]
@DeysonOrtiz Do you want to notify all users?

**Comment by DeysonOrtiz** [comment]
@ravinderk   Yes, I was hoping to add something like social sites, that have a new post notification, so my customers can see when certain pages have new comments.  I have 2 pages for discussions and new product requests.    Thank you :)

**Comment by ravinderk** [comment]
@DeysonOrtiz This repo created for learning purpose.
I think this WordPress theme https://wordpress.org/themes/p2/ does something like this, but to understand you have to dig into code
